### ISSUE TITLE
Problem with long XML text

### ISSUE THREAD

**Issue by lippomano** [MurhafSousli/ngx-highlightjs#100]
```
- [ ] bug report -> please search issues before submitting
- [ X] feature request
- [ ] question
```

### OS and Version?
Windows 10

### Problem

I have a long XML text (about 3000 lines) but for some reason when I try to highlight it freeze and I can't do anything

**Comment by MurhafSousli** [comment]
This isn't related to this plugin, you should open your issue on https://github.com/highlightjs/highlight.js/

**Comment by yyyc514** [comment]
@MurhafSousli What makes you certain it's an upstream problem?  I can't reproduce on either master or 9.17.1.

Are you bundling a very old version I should test against?

**Comment by MurhafSousli** [comment]
@yyyc514  When a user installs this package, it will automatically install the latest version of `higlight.js` at the time he installed it.

https://github.com/MurhafSousli/ngx-highlightjs/blob/9491d7704e3f37bc0788607813fb628437b1c881/projects/ngx-highlightjs/package.json#L27-L35

**Comment by MurhafSousli** [comment]
If the user installed this package a long time ago, he should re-install `highglight.js` manually to get the latest version.

Moreover, the user can use his own version of `highlight.js` if he wants by just adding its script in the document head.

But this `ngx-highlightjs` is no more than a wrapper plugin for `highlight.js` so this issue 100% not related to this package.
