### ISSUE TITLE
[Bug] External resources from <link> tags are getting loaded

### ISSUE THREAD

**Issue by Akuka** [MurhafSousli/ngx-highlightjs#101]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
macOS

### Versions
"ngx-highlightjs": "^4.0.0"

### Repro steps
After upgrade from version 3.0.3 to 4.0.0, when the code (e.g HTML) contains tags like `<link>`, instead of only present the code, this library actually running it - that means the browser trying to load the javascript/css files from the `href` of those tags. 
e.g
`<link href="https://example.com/example01.css" rel="stylesheet" type="text/css" />`
or 
`<link rel="preload" href="https://example.com/example02.js" as="script" />`

### Mention any other details that might be useful
This bug is also a security vulnerability that can cause malicious code to run on your website unintentionally

**Comment by MurhafSousli** [comment]
Sorry, I didn't understand, what do you mean by it runs a link tag in the HTML? are link tags runnable?

Can you add a reproduction of your issue in this [stackblitz](https://stackblitz.com/edit/ngx-highlightjs) and highlight what is going wrong using a screenshot?

**Comment by Akuka** [comment]
The only change I made is in lines 13-16 (change the value of the `code` variable)
![Screen Shot 2019-12-31 at 16 14 50](https://user-images.githubusercontent.com/3299903/71624047-47c9c000-2be9-11ea-9f4c-3c5280854415.png)

**Comment by MurhafSousli** [comment]
Ah ok, now I understand. If this is not handled by the highlight.js library then we should add an extra layer of protection from the HTML value.

In this package, the highlight directive uses `nativeElement.innerHTML` to set the highlighted code from _highlight.js library_ , I think using the DOM sanitizer will fix the issue, not sure if it will bypass the highlighted code but will give it a try

**Comment by Akuka** [comment]
Yap, this line:
https://github.com/MurhafSousli/ngx-highlightjs/compare/v3.0.3...v4.0.0#diff-8c56a5e0924ee4f79bd2f8c7474bf57cR106

**Comment by MurhafSousli** [comment]
Fixed in v4.0.1

**Comment by Akuka** [comment]
Hi, 
It looks like the issue was not completely fixed.
I tried it with the following code:
```
code = `<img src="https://example.com/example.jpg"/>`
```

Attached screenshot:
![Screen Shot 2020-01-01 at 11 50 50](https://user-images.githubusercontent.com/3299903/71640191-d728af00-2c8d-11ea-9e56-40f9a49cc8a7.png)

**Comment by MurhafSousli** [comment]
The same code is working properly on my end, please make a fork and attach the link, the would make the process much easier for me!

**Comment by Akuka** [comment]
> The same code is working properly on my end, please make a fork and attach the link, the would make the process much easier for me!

Please:
https://stackblitz.com/edit/ngx-highlightjs-pcuh7u

**Comment by MurhafSousli** [comment]
The link and script was fixed, but the `img` was not, I am not sure why! it is weird because the HTML added does not evaluate to an img element at all. why is it trying to fetch the URL

I added reproduction here https://stackblitz.com/edit/ngx-highlightjs-ydbmxc?file=src/app/home/home.component.ts

**Comment by Akuka** [comment]
So do you want me to open a new issue, or do you want to reopen this issue?

**Comment by MurhafSousli** [comment]
Yes, that would be better! thanks for reporting
