### ISSUE TITLE
[Bug] External resources from <img> tags are getting loaded

### ISSUE THREAD

**Issue by Akuka** [MurhafSousli/ngx-highlightjs#105]
After upgrade from version 3.0.3 to 4.0.1, when the code (e.g HTML) contains tags like `<img>`, instead of only present the code, this library actually loading the images.
e.g
`<img src="https://example.com/example.jpg"/>`

a reproduction here: https://stackblitz.com/edit/ngx-highlightjs-ydbmxc?file=src/app/home/home.component.ts

Attached screenshot:
![Screen Shot 2020-01-01 at 11 50 50](https://user-images.githubusercontent.com/3299903/71640191-d728af00-2c8d-11ea-9e56-40f9a49cc8a7.png)

_Originally discussed at https://github.com/MurhafSousli/ngx-highlightjs/issues/101#issuecomment-570038963_

**Comment by MurhafSousli** [comment]
Fixed in v4.0.2, A [fixed stackblitz](https://stackblitz.com/edit/ngx-highlightjs-ydbmxc?file=src%2Fapp%2Fhome%2Fhome.component.ts) with v4.0.2
