### ISSUE TITLE
Not displaying line numbers

### ISSUE THREAD

**Issue by mikezero84** [MurhafSousli/ngx-highlightjs#109]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10

### Versions
angular cli 8.3.19
npm 6.12.0

### Repro steps
I setup the module:

`import { HighlightModule, HIGHLIGHT_OPTIONS  } from 'ngx-highlightjs';
providers: [
        ...,
        {
            provide: HIGHLIGHT_OPTIONS,
            useValue: {
                lineNumber: true
            } 
        }
    ],`

In the html i put:
`<pre><code [highlight]="code" [lineNumbers]=true></code></pre>`

But it's not displaying the lines number, what I missing, I followed the usage instructions.

### The log given by the failure
no log failure

### Desired functionality
Display line numbers

### Mention any other details that might be useful
no link available

**Comment by MurhafSousli** [comment]
Your code is correct, but maybe the package `highlightjs-line-numbers.js` was not installed for some reason, try to install it manually `npm i highlightjs-line-numbers.js` and try again.

**Comment by nrevutsky** [comment]
Should be 
`useValue: { lineNumbers: true }`
instead of `useValue: { lineNumber: true }`
Documentation is missing **S** letter too.

**Comment by MurhafSousli** [comment]
It is fixed now

**Comment by nrevutsky** [comment]
Thanks, would be great to get it fixed at [npmjs.com](https://www.npmjs.com/package/ngx-highlightjs) too

**Comment by MurhafSousli** [comment]
It isn't a code fix, there is no need for releasing a new version for a 1 letter typo. in fact, it's already fixed  in the options section https://www.npmjs.com/package/ngx-highlightjs#options

**Comment by dnmd** [comment]
Just a quick addition, if you declare the provider inside a lazy loaded component, the page numbers are not displayed. I only got it working when;

adding the following to the `app.module.ts`

````javascript
import { HIGHLIGHT_OPTIONS } from 'ngx-highlightjs';
...
{
  provide: HIGHLIGHT_OPTIONS,
  useValue: {
    lineNumbers: true
  }
}
````

and in the lazy component module (e.g. `home.module.ts`)

````javascript
import { HighlightModule } from 'ngx-highlightjs';
...
@NgModule({
  imports: [
    ...
    HighlightModule,
    ...
   ]
...
})
````

It might be worth adding to the docs
