### ISSUE TITLE
Highlight all child code elements

### ISSUE THREAD

**Issue by thesunnypro** [MurhafSousli/ngx-highlightjs#110]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### Versions
ngx-highlightjs - v4

### Desired functionality

Highlight all child code elements that were earlier present in [v2 version](https://github.com/MurhafSousli/ngx-highlightjs/blob/master/README_v2.md). 

I am looking to highlight the code between the child tags- `<pre><code></code></pre>`

v2 had this implementation working well. 
```
<div highlight="all">
  <pre><code [textContent]="htmlCode"></code></pre>
  <pre><code [textContent]="tsCode"></code></pre>
  <pre><code [textContent]="cssCode"></code></pre>
</div>
```

**Comment by MurhafSousli** [comment]
it is deprecated https://github.com/MurhafSousli/ngx-highlightjs/blob/master/CHANGELOG.md#breaking-changes

You can still use highlight them manually using the hljs functions
```ts
constructor(private hljs: HighlightJS) { }

ngAfterViewInit() {
  this.hljs.initHighlighting().subscribe();

  // or

   document.querySelectorAll('pre').forEach(item => {
      this.hljs.highlightBlock(item).subscribe();
    });
}
```
