### ISSUE TITLE
codeFromUrl pipe not working with Raw URL

### ISSUE THREAD

**Issue by betancourtc** [MurhafSousli/ngx-highlightjs#112]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
```
Windows 10
```

### Versions
```
Angular CLI: 9.0.1
Node: 12.13.0
OS: win32 x64
```

### Repro steps

Not working when codeUrl equals to the Raw URL.

`codeUrl = '/example/text.html'` 

`<pre><code [highlight]="codeUrl | codeFromUrl | async" ></code></pre>`

### The log given by the failure
No error in console

### Desired functionality
Display code from raw url 

### Mention any other details that might be useful
Works if using URL (instead of raw URL). Usage under instructions state that Raw URL should be passed to the codeFromUrl pipe.

`codeUrl = 'http:///test.com/example/text.html'`

**Comment by MurhafSousli** [comment]
It seems that ivy is crashing when used with more than one pipe

**Comment by MurhafSousli** [comment]
Try to reproduce with v4.1.0 using a stackbltiz, closing...

**Comment by Eve-Sama** [comment]
It happens to me. 

Below way not works

      codeUrl = './xxxx.component.html';

But below way works

      codeUrl = 'https://xxx.xxx.component.htm';

How can I read relative file?
