### ISSUE TITLE
Language import not working in strict mode

### ISSUE THREAD

**Issue by fclmman** [MurhafSousli/ngx-highlightjs#115]
### Bug Report or Feature Request (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 10
### Versions

Angular CLI: 9.0.5
Node: 12.4.0
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

### Repro steps

yarn add --dev @types/highlight.js

export function getHighlightLanguages() {
  return {
    xml: () => import('highlight.js/lib/languages/xml'),
    scss: () => import( 'highlight.js/lib/languages/scss')
  };
}

@NgModule({
  imports: [
    HighlightModule
  ],
  providers: [
    {
      provide: HIGHLIGHT_OPTIONS,
      useValue: {
        languages: getHighlightLanguages()
      }
    }
  ],
  bootstrap: [AppComponent]
})
export class AppModule {
}

and "noImplicitAny": true in tsconfig.json

### The log given by the failure

Could not find a declaration file for module 'highlight.js/lib/languages/xml'. '.../node_modules/highlight.js/lib/languages/xml.js' implicitly has an 'any' type.
  Try `npm install @types/highlight.js` if it exists or add a new declaration (.d.ts) file containing `declare module 'highlight.js/lib/languages/xml';`

### Desired functionality

It is expected to work

**Comment by MurhafSousli** [comment]
I am not sure what causes the error, please try to investigate this issue and let me know if it is caused by the library

**Comment by sfabriece** [comment]
My solution is to create a `typings.d.ts` under src.
 In this file add the path to the languages

example:

```ts
declare module 'highlight.js/lib/languages/xml';
declare module 'highlight.js/lib/languages/typescript';

```

**Comment by DmitryEfimenko** [comment]
these definitions need to be provided by the library. Not sure which one though - `ngx-highlightjs` or `highlight.js`

**Comment by MurhafSousli** [comment]
@DmitryEfimenko these comes with `highlight.js` but it is js and has not types out of the box

**Comment by Razzeee** [comment]
`import 'highlight.js';`

Adding this line in my `shared.module.ts` seems to get rid of the warnings.

**Comment by pranav-js** [comment]
@razzeee  thanks man , worked for me !
