### ISSUE TITLE
Getting TS1086 error

### ISSUE THREAD

**Issue by yonimoses** [MurhafSousli/ngx-highlightjs#120]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

 macOS(Cataline)

### Versions
Angular CLI: 8.3.25
Node: 13.7.0

Hi
Tried to work with the package and got the following error.
I've also installed highlightjs ^9.18.1 .

### The log given by the failure
ERROR in node_modules/ngx-highlightjs/lib/highlight.service.d.ts:7:9 - error TS1086: An accessor cannot be declared in an ambient context.

7     get hljs(): HighlightLibrary | null;
          ~~~~

any idea on how to overcome ?

**Comment by MurhafSousli** [comment]
Please add the version of the library which you installed, and a reproduction stackblitz for the issue

**Comment by yonimoses** [comment]
Version is the latest . 4.1.0-beta.
as for reproduction, might take a while as i need to extract entire codebase for it.

Any ideas i can quick try?

**Comment by Polidoro** [comment]
This appears to be a problem with Typescript versions < 3.7, which is makes it a problem for Angular versions < 9.

There are a few recommendations here but I haven't tried any of them yet so I can't verify if they work:
https://stackoverflow.com/questions/58802463/types-sequelize-error-ts1086-an-accessor-cannot-be-declared-in-ambient-context/58804230#58804230

**Comment by MurhafSousli** [comment]
This look like a typescript issue! I really have no idea how to overcome this. maybe you just need to update to latest angular / typescript versions.

**Comment by pek77** [comment]
This problem still exist on Angular 8
