### ISSUE TITLE
npm WARN ngx-highlightjs@4.0.2 requires a peer of @angular/common@^8.0.0, @angular/core@^8.0.0

### ISSUE THREAD

**Issue by suhailkc** [MurhafSousli/ngx-highlightjs#123]
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
macOS Catalina

### Versions
Angular CLI: 9.1.0
Node: 12.14.0
OS: darwin x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0

### Repro steps
npm install

### The log given by the failure
Showing warnings when npm install
`npm WARN ngx-highlightjs@4.0.2 requires a peer of @angular/common@^8.0.0 but none is installed. You must install peer dependencies yourself.`

`npm WARN ngx-highlightjs@4.0.2 requires a peer of @angular/core@^8.0.0 but none is installed. You must install peer dependencies yourself.`

### Desired functionality
Showing warnings when npm install

### Mention any other details that might be useful
Are these warnings are dangerous?

**Comment by MurhafSousli** [comment]
No, if you don't want to see these warning install the latest version `4.1.0-beta`
