### ISSUE TITLE
Enable in <pre> tags in string

### ISSUE THREAD

**Issue by MehmetSert** [MurhafSousli/ngx-highlightjs#125]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

I have content from the api. I show this content with [innerHTML]. There are sections in it with the pre tag. I want to activate your plugin in these tags as well.
So the value of my variable is string. There are html codes in it. But this content comes to me via api. So I can't add the [highlight] directive.

How can I do that?

### Versions
```
Angular CLI: 8.3.25
Node: 10.14.2
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.25
@angular-devkit/build-angular              0.803.25
@angular-devkit/build-optimizer            0.803.25
@angular-devkit/build-webpack              0.803.25
@angular-devkit/core                       8.3.25
@angular-devkit/schematics                 8.3.25
@angular/cdk                               7.3.4
@angular/cli                               8.3.25
@angular/material                          7.3.4
@angular/pwa                               0.901.1
@ngtools/webpack                           8.3.25
@nguniversal/express-engine                7.1.1
@nguniversal/module-map-ngfactory-loader   7.1.1
@schematics/angular                        8.3.25
@schematics/update                         0.803.25
rxjs                                       6.5.4
typescript                                 3.5.3
webpack                                    4.39.2

```

### Stackblitz Demo
https://stackblitz.com/edit/ngx-highlightjs-g2mvdz?file=src%2Fapp%2Fhome%2Fhome.component.html

**Comment by MurhafSousli** [comment]
In this case, it is better for you to use a directive instead of the pipe `keepHtml` and once the content HTML is set. you can call the library service on the native element 

https://github.com/MurhafSousli/ngx-highlightjs/blob/master/projects/ngx-highlightjs/src/lib/highlight.service.ts#L78

**Comment by MehmetSert** [comment]
Thank you.
I updated it on demo address so that those in need can benefit.
