### ISSUE TITLE
Feature request : enlarge or create a margin between line numbers and highlighted text

### ISSUE THREAD

**Issue by pfouque06** [MurhafSousli/ngx-highlightjs#128]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```

### OS and Version?

any OS
### Versions

Angular CLI: 9.0.7
Node: 12.16.3
OS: linux x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2

### Repro steps

used codeing guide from your tutorial and it happens that there is no margin between line numbering and the text with my implementation. Therefore, that compells me to add manual spacing on source context itself.

**Comment by MurhafSousli** [comment]
This issue is out of the plugin scope, you can refer to the original line script numbers for support https://github.com/wcoder/highlightjs-line-numbers.js
