### ISSUE TITLE
Highlighting big JSON data freezes the browser

### ISSUE THREAD

**Issue by renankaic** [MurhafSousli/ngx-highlightjs#138]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```
I would like to highlight big JSON datas, with more than 20,000 lines. When I try to highlight it, the browser tab freezes.

### OS and Version?

Windows 10 1803

### Versions

Angular CLI: 10.0.3
Node: 12.14.1
OS: win32 x64

Angular: 10.0.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.3
@angular-devkit/build-angular     0.1000.3
@angular-devkit/build-optimizer   0.1000.3
@angular-devkit/build-webpack     0.1000.3
@angular-devkit/core              10.0.3
@angular-devkit/schematics        10.0.3
@angular/cdk                      10.1.1
@angular/cli                      10.0.3
@angular/material                 10.1.1
@ngtools/webpack                  10.0.3
@schematics/angular               10.0.3
@schematics/update                0.1000.3
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

### Repro steps

1 - Run `git clone https://github.com/renankaic/ngx-highlights-big-json-data-issue` in any folder
2 - Go to the created folder and run `npm install`
3 - Run `npm start`
4 - Access http://localhost:4200
5 - Click the buttons to get the data with and without Highlights

### The log given by the failure

No log, no errors -- it only freezes the application

### Desired functionality

I would like to show big JSON datas inside the HTML `<code>` tag with Highlighting without freezing the browser.

### Mention any other details that might be useful

The browser doesn't freeze if I don't use the highlight feature from ngx-highlights

**Comment by MurhafSousli** [comment]
I would not doubt it if you are loading a 20,000 lines of code in one file! regardless of your use case, you should open this issue on the official plugin, this project is just a wrapper plugin.
