### ISSUE TITLE
Custom tags -> wrong coloring

### ISSUE THREAD

**Issue by MichalNemec** [MurhafSousli/ngx-highlightjs#139]
### Bug Report or Feature Request (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Windows 10

### Versions

Angular CLI: 10.0.5
Node: 12.18.2
OS: win32 x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router     
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        10.0.5
@angular/cdk                      10.1.2
@angular/cli                      10.0.5
@angular/material                 10.1.2
@ngtools/webpack                  10.0.5
@schematics/angular               10.0.5
@schematics/update                0.1000.5
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

### Repro steps

<yada-menu>
    <yada-menu-profile src="http://placehold.it/70x70" link="string" size="70"></yada-menu-profile>
    <yada-menu-notify count="1" link="string" data="object"></yada-menu-notify>
    <yada-menu-toggle data="object"></yada-menu-toggle>
  </yada-menu>

### The log given by the failure

![FireShot Capture 008 - NexOptComponents - localhost](https://user-images.githubusercontent.com/5663019/89577939-b5019b80-d831-11ea-8906-6de7f178b6da.png)

### Desired functionality

See properly colored code

**Comment by MurhafSousli** [comment]
You should open such issue on the official issue https://github.com/highlightjs/highlight.js
