### ISSUE TITLE
code block is not styled correctly

### ISSUE THREAD

**Issue by Steinente** [MurhafSousli/ngx-highlightjs#140]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
> Windows 10

### Versions
Angular CLI: 9.0.7
Node: 10.13.0
OS: win32 x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.5
typescript                        3.7.5
webpack                           4.41.2

### Repro steps
module.ts
![module ts](https://user-images.githubusercontent.com/42090794/89870069-98f55580-dbb5-11ea-93ec-ac81557a44b6.PNG)

component.html
![component html](https://user-images.githubusercontent.com/42090794/89870177-c0e4b900-dbb5-11ea-9236-576b81b8bc79.PNG)

component.ts
![component ts](https://user-images.githubusercontent.com/42090794/89870310-ed98d080-dbb5-11ea-8ff0-57a20cf4b2c4.PNG)

angular.json
`
            "styles": [
              "src/styles.scss",
              "node_modules/highlight.js/styles/github.css"
            ],
`

Result
![res](https://user-images.githubusercontent.com/42090794/89869443-a5c57980-dbb4-11ea-8d90-c68a6f3ec43d.PNG)

I restarted the app several times and went through the installation guide several times. Unfortunately it does not work.

**Comment by MurhafSousli** [comment]
Remove the languages input as the directive autodetect the language
