### ISSUE TITLE
A large number of rows are not displayed.

### ISSUE THREAD

**Issue by Arap919** [MurhafSousli/ngx-highlightjs#144]
I wanted to show responsive table markup in storybook but I've got a trouble. All lines of code are not displayed.
Simple example is here https://stackblitz.com/edit/ngx-highlight-js-akewwt?file=src/app/app.component.html

**Comment by MurhafSousli** [comment]
Please open your issue on the official plugin page https://github.com/highlightjs/highlight.js/

This repo is just a wrapper plugin and it doesn't change the functionality
