### ISSUE TITLE
Should specifying language class work?

### ISSUE THREAD

**Issue by KensingtonTech** [MurhafSousli/ngx-highlightjs#148]
### Bug Report or Feature Request
```
- [x] question
```

### OS and Version?
MacOS Catalina

### Versions
Angular CLI: 10.1.4
Node: 14.14.0
OS: linux x64

Angular: 10.1.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.4
@angular-devkit/build-angular   0.1001.4
@angular-devkit/core            10.1.4
@angular-devkit/schematics      10.1.4
@angular/cdk                    10.2.3
@schematics/angular             10.1.4
@schematics/update              0.1001.4
rxjs                            6.5.5
typescript                      3.9.7

### Repro steps
N/A

### The log given by the failure
N/A

### Desired functionality
The highlight.js library allows one to manually specify the language, overriding auto-detection, by adding class 'language-<languagename>' to the 'code' element.  Is that functionality still expected to work with ngx-highlightjs?  I ask ask because it isn't working for me, but before I go raising it as a bug either here or with highlight.js, I'd like to know whether this is still expected to work.  Thank you!

### Mention any other details that might be useful
N/A

**Comment by MurhafSousli** [comment]
No, ngx-highlightjs uses the `highlightAuto()` function which adds the class after detecting the language. you can however still use the other library's functions using `HighlightJS` service provided in this package outside the highlight directive.
