### ISSUE TITLE
Theme option in directive

### ISSUE THREAD

**Issue by vasiltabakov** [MurhafSousli/ngx-highlightjs#15]
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] question
```
It would be great if the directive has a way of specifying different themes. Something like:
```
<code highlight [theme]="'github'" ...
<code highlight [theme]="'agate'" ...

**Comment by MurhafSousli** [comment]
Hi @vasiltabakov 
That doesn't seem to be applicable right away because these themes are the stylesheets provided by _highlightjs_, if you load 2 stylesheets they will override each other.

**Comment by vasiltabakov** [comment]
Ah, you're right. Luckily it seems themes are very short (100 lines of code in the one we use), so we'll come up with some hack of our own. I'm thinking theme 'wrapper' css class and our own theme definitions. Guess nothing the angular lib could help with.
