### ISSUE TITLE
Refresh highlight view

### ISSUE THREAD

**Issue by kek-Sec** [MurhafSousli/ngx-highlightjs#177]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x] question
```

### OS and Version?
> Windows 7, 8 or 10. 

### Versions

Angular CLI: 12.1.0-next.3
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 ia32

### Repro steps
Changing the content of the code variable does not lead to refreshing of the  pre/highlighted text

https://github.com/kek-Sec/xml-prettify/blob/main/src/app/output/output.component.ts

### The log given by the failure
no error is produced

### Desired functionality

is it possible to refresh the view manually?

**Comment by kek-Sec** [comment]
I can make a reproduction stack blitz if needed but it's quite simple,take your example and change the code variable after the onInit function e.x. a button

**Comment by MurhafSousli** [comment]
Just reproduce it then https://stackblitz.com/edit/ngx-highlightjs

**Comment by kek-Sec** [comment]
I apologize it seems to be a problem with material-stepper with ngx-highlights

stackblitz tests run fine -> https://ngx-highlightjs-qgvcfh.stackblitz.io
