### ISSUE TITLE
error NG6002: Appears in the NgModule.imports of MyModule, but itself has errors

### ISSUE THREAD

**Issue by FrancescoBorzi** [MurhafSousli/ngx-highlightjs#178]
I got this failure when upgrading from version 3 to version 4 of ngx-highlightjs in my Angular 12 app

Full code: https://github.com/azerothcore/Keira3/pull/1281

#### Reproduction

Steps to reproduce:
1. `git clone git@github.com:azerothcore/Keira3.git; cd Keira3`
2. `npm install`
3. `npm start`
 
 
#### Expected Behavior

It should compile and run.

#### Actual Behavior

It fails with errors such as:

```
Error: src/app/shared/modules/sai-editor/sai-editor.module.ts:32:14 - error NG6002: Appears in the NgModule.imports of SaiCreatureModule, but itself has errors

32 export class SaiEditorModule {}
                ~~~~~~~~~~~~~~~
```

#### Environment

```
Angular CLI: 12.0.3
Node: 14.15.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 12.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.3
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.3
@schematics/angular             12.0.3
rxjs                            6.6.7
typescript                      4.2.4

```

**Comment by MurhafSousli** [comment]
I cannot look into that, it could be caused by your project settings or other code, I need a stackblitz reproduction to look into it!

**Comment by FrancescoBorzi** [comment]
fixed, thanks for your help @MurhafSousli , much appreciated.
