### ISSUE TITLE
Support For Angular 4

### ISSUE THREAD

**Issue by madara134** [MurhafSousli/ngx-highlightjs#19]
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Versions

@angular/cli: 1.0.1
node: 7.10.0
"os": win32 x64
"angular/animations": 4.1.0
"angular/common": 4.1.0
"angular/compiler": 4.1.0
'angular/core": 4.1.0
"angular/forms": 4.1.0
"angular/http": 4.1.0
"angular/platform-browser": 4.1.0
"angular/platform-browser-dynamic": 4.1.0
"angular/platform-server": 4.1.0
"angular/router": 4.1.0
"angular/cli": 1.0.1
"angular/compiler-cli": 4.1.0

### Desired functionality
ERROR in Metadata version mismatch for module xxx/web/node_modules/ngx-highlightjs/ngx-highlightjs.d.ts, found version 4, expected 3, resolving symbol

**Comment by MurhafSousli** [comment]
Not gonna happen
