### ISSUE TITLE
Select programming language

### ISSUE THREAD

**Issue by LuisJoseSanchez** [MurhafSousli/ngx-highlightjs#20]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] question
```

### OS and Version?

Ubuntu Linux 17.10

### Versions

Angular CLI: 1.5.0
Node: 8.9.3
OS: linux x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.0
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.0
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.8.1

### Desired functionality

It should be a great improvement to select the programming language.
For example:

```
<pre><code highlight [code]="someJavaCode" [language]="java"></code></pre>
<pre><code highlight [code]="someConsoleCommands" [language]="console"></code></pre>
```

Now, if you write console commands in your text, you have different colors in the same line which looks very strange.

**Comment by MurhafSousli** [comment]
Hi @LuisJoseSanchez 
I added `[language]` input in **v1.4.0**
However this option is only to restrict detection of the language, see [highlightauto docs](http://highlightjs.readthedocs.io/en/latest/api.html#highlightauto-value-languagesubset)

Use it like `[language]="['java']"`

**Comment by LuisJoseSanchez** [comment]
Thanks for your answer.

Sorry, it doesn't work for me.

When I write:

```
<pre><code highlight [code]="javaCode" [language]="['java']"></code></pre>
```

I get this error:

```
Error: Template parse errors:
Can't bind to 'language' since it isn't a known property of 'code'. ("

<pre>
  <code highlight [code]="code" [ERROR ->][language]="['java']"></code>
</pre>"): ng:///AppModule/SourceCodeComponent.html@12:32
```

**Comment by MurhafSousli** [comment]
@LuisJoseSanchez maybe you didn't update to v1.4.0 properly, take a look at this [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-ft6pjt?file=app/home/home.component.html)

**Comment by LuisJoseSanchez** [comment]
Ok, perfect. Now I have v1.4.0 and works good.

Thank you very much!

**Comment by MatthewLHolden** [comment]
I have the following code:

`<pre><code highlight [code]="code" [language]="['html']" (highlighted)="onHighlight($event)"></code></pre>`

...

code = `<div class="something"></div>`;

...

> Can't bind to 'code' since it isn't a known property of 'code'.


Running "highlight.js": "9.13.1" & "ngx-highlightjs": "3.0.0"

Any ideas on how to resolve this? Currently typescript and CSS are styled but HTML isn't.

E.g of working: 

`<pre><code [highlight]="component.typescript" (highlighted)="onHighlight($event)"></code></pre>`

**Comment by MurhafSousli** [comment]
@MatthewLHolden Make sure highlightjs is imported

**Comment by MatthewLHolden** [comment]
Hi, I have the following imported in my component and module:

import { HighlightResult } from 'ngx-highlightjs';

**Comment by alwinaugustin** [comment]
I am also getting the same error. I have installed the JS file in the module providers section, but it is not working.
