### ISSUE TITLE
Highlight.js library was not imported and cannot read property 'themePath' of undefined

### ISSUE THREAD

**Issue by GregoireLgt** [MurhafSousli/ngx-highlightjs#207]
- [x] bug report 
- [ ] feature request
- [ ] question

#### Repro steps

1) Install ngx-hightlightjs 6.1.0

2) Add the following to app.module.ts:

```ts
import {HighlightModule, HIGHLIGHT_OPTIONS} from 'ngx-highlightjs';

imports: [
    ...
    HighlightModule
  ],
providers: [
    ...
    {
      provide: HIGHLIGHT_OPTIONS,
      useValue: {
        coreLibraryLoader: () => import('highlight.js/lib/core'),
        languages: {
          xml: () => import('highlight.js/lib/languages/xml')
        }
      }
    }
  ],
```

#### Console logs
![image](https://user-images.githubusercontent.com/47480030/148098024-f65b8576-1818-4b15-895e-edd576ae2454.png)

Debug mode : 
![image](https://user-images.githubusercontent.com/47480030/148098236-803547ba-cd97-402e-a7ff-d6e7f98e1ddd.png)

#### Environment

- Angular: 13
- ngx-highlightjs: 6.1.0
- Browser(s): Chrome 87.0.4280.141 (Build officiel) (32 bits)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10 Professionnel

**Comment by MurhafSousli** [comment]
This error is because your project is missing the original package `npm i highlight.js` 

It is weird because it should be installed automatically!

**Comment by GregoireLgt** [comment]
Hi, 

I am sorry but highlight.js is already installed and i am still getting these weird errors :(

**Comment by MurhafSousli** [comment]
It depends how you are importing it, you should provide that hljs token in the root module.

**Comment by GregoireLgt** [comment]
The HLJS token you are talking about is the HIGHLIGHT_OPTIONS token ? If yes, i use it as a provider in the app.module.ts

**Comment by GregoireLgt** [comment]
Hi @MurhafSousli, sorry to insist but the 6.0.0 of your package works like a charm whereas the 6.1.0 and above are not working anymore with the 'cannot read property themePath of null' error :(

Regards,

**Comment by MurhafSousli** [comment]
@GerkinDev Sure thing! the injection token should be used in the root module only! but the module can be imported at child module level.

That's why I didn't introduce `HighlightModule.withConfig()` so users don't make the mistake of setting the config in child module

**Comment by GerkinDev** [comment]
Yeah I get your point, but in my case, I use this module in my dev tools, and I'd like to not ship it at all in the main bundle. Thus, including it in the root module is not an option for me.

**Comment by MurhafSousli** [comment]
@GerkinDev You are not shipping it using the injection token! you are only passing a function that returns a promise which will load the library. so it won't be included in your main script.

Can you show that it is increasing it?

**Comment by GerkinDev** [comment]
It must. The injection token declaration, along with the configured value & imports declaration processed by webpack ARE in the root module output.

This is not even close to the size of the full lib, I know. But still, there is a hard reference to multiple files, including highlightjs & your module, anyway. Tree shaking should make it as small as possible, just a few bytes, but a few bytes used by 0.01% of users isn't really worth it.

Moreover, if your module is shipped conditionally (in dev environment only for example), constraining its declaration in the root module can be troublesome, though I suppose there are handy ways to come around this.

Still. I'll go with my fork changing the providers scope.

**Comment by MurhafSousli** [comment]
@GerkinDev When webpack process the import script, it will only include that script in the dist directory, but won't merge it in the main script, meaning that the script won't slow the app launch. it will be loaded separately on parallel with the loader service.

If you are referring to the few bytes reserved for the config value the user pass, like the script string path, that is does not worth lazy loading in my opinion.

But anyway, is removing the `providedIn: root` from the services your proposal?

**Comment by GerkinDev** [comment]
Are there any real downside you expect, that I should be aware of to consider declaring providers is a necessity ?

**Comment by MurhafSousli** [comment]
Not really! the only thing that matters is that it should not load the script twice if the highlight module is being used in different lazy modules. that's why I choice a singleton service.

**Comment by GerkinDev** [comment]
Well, Highlight.js is not exported via UMD globals, yet, I see in your loader service that you expose it as global if using line numbers plugin. Maybe this could be used also to check if the lib was already loaded.
Globals are evil. But here, we're talking about replacing a global service with a global variable.

Or maybe another service could be globally used without any dependency, that serves just as a memo for configured loaders. Dunno

**Comment by GerkinDev** [comment]
I was talking about those, that force the loader to have `HIGHLIGHT_OPTIONS` provider in scope: 

https://github.com/MurhafSousli/ngx-highlightjs/blob/c1229aa2f914f8be74ed6d0f5066b1c2856c2050/projects/ngx-highlightjs/src/lib/highlight.loader.ts#L22-L24
