### ISSUE TITLE
Support loading of relative URLs

### ISSUE THREAD

**Issue by jasomimo** [MurhafSousli/ngx-highlightjs#224]
#### Feature Description

When a relative URL is passed into `codeFromUrl` pipe, then file is not fetched.

```
<pre>
    <code [highlight]="'/assets/examples/foo.html' | codeFromUrl | async"></code>
</pre>
```

Let's say user would like to fetch a file from assets folder, but don't want to build full URL (maybe there is too many examples in assets, or they don't know on which domain will be the app deployed to). 

If `codeFromUrl` pipe would support relative paths, it would be possible to reference the file only by a path which is starting from the assets folder. And that path would never change.

[`HighlightOptions`](https://github.com/MurhafSousli/ngx-highlightjs/blob/c1229aa2f914f8be74ed6d0f5066b1c2856c2050/projects/ngx-highlightjs/src/lib/highlight.model.ts#L126) interface might be enriched with `baseUrl: string` configuration option, where user could set the base path for relative URLs, e.g. `https://example.com/my-app`.

#### Use Case

This would allow to more easily reference files deployed on the same domain.

**Comment by exodussystem** [comment]
I would  like the same feature as well.

Basically if the module provides a way to set URL patterns that can be used in this function, then it should be fine

[code-loader.ts]
function isUrl(url: string) {
  const regExp = /(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/;
  return regExp.test(url);
}

**Comment by MurhafSousli** [comment]
Fixed in v11, you can now use relative path like this

```html
<pre>
    <code [highlight]="'assets/examples/foo.html' | codeFromUrl | async"></code>
</pre>
```
