### ISSUE TITLE
Binding data from innerHtml

### ISSUE THREAD

**Issue by peripurnama** [MurhafSousli/ngx-highlightjs#246]
#### Feature Description

Binding data from innerHtml

### How to enter this html code

```
const fullContent = `<p>Test Syntax</p>
<pre><code [highlight]="`public class HelloWorld {
    public static void main(String[] args) {
        System.out.println(&quot;Hello World&quot;);
    }
}`" [languages]="['java']" 
(highlighted)="onHighlight($event)" [lineNumbers]="false"></code></pre>`;
```

**from the code above this line that you want to highlight:**

```
`public class HelloWorld {
    public static void main(String[] args) {
        System.out.println(&quot;Hello World&quot;);
    }
}`
```

`<div [innerHtml]="fullContent | safeMode"></div>`

Tampilan yg di harapkan

<img width="476" alt="Screenshot 2023-01-01 214822" src="https://user-images.githubusercontent.com/35743609/210174787-3f73aa12-e89d-4d06-b72a-6e590403ed36.png">

**Comment by MurhafSousli** [comment]
You can already do that, however, you need to use [highlight service](https://github.com/MurhafSousli/ngx-highlightjs/blob/master/projects/ngx-highlightjs/src/lib/highlight.service.ts)  and manually highlight using `highlightAll` or `highlightElement` functions

**Comment by peripurnama** [comment]
i tried the manual way with this code it works, but in the browser there is a warning

```
var blocks = this.elementRef.nativeElement.querySelectorAll('pre code');
    blocks.forEach((block:any) => {
      this.highlightJS.hljs?.highlightElement(block);
});
```

One of your code blocks includes unescaped HTML. This is a potentially serious security risk.

**Comment by peripurnama** [comment]
I found a solution, you can use this method,
maybe in the library you can add this directive

```
@Pipe({ name: "safeHtml" })
export class SafeHtmlPipe implements PipeTransform {
  constructor(private sanitizer: DomSanitizer) {}

  transform(value:any) {
    return this.sanitizer.bypassSecurityTrustHtml(value);
  }
}

@Pipe({
  name: 'highlightCode',
})
export class HighlightCodePipe implements PipeTransform {

  constructor(private highlightJS: HighlightJS,
    private sanitizer: DomSanitizer){
  }

  transform(htmlMarkup: string): string {
    const preCodeRegex = /<pre><code(?: class="language-(.*)")?>([\s\S]*?)<\/code><\/pre>/g;

    let result = htmlMarkup.replace(preCodeRegex,  (_match, languageName, codeBlock) => {
      let codeBlockHighlighted: string = '';
      if (!languageName) {
        codeBlockHighlighted = hljs.highlightAuto(codeBlock, ['java']).value || ''
      } else {

        codeBlockHighlighted = hljs.highlight(codeBlock, {
          language: languageName,
          ignoreIllegals: true
        }).value || '';
        
      }

      const code = '<pre><code class="hljs">' + codeBlockHighlighted + '</pre></code>';
      
      return code;
    });
    return result;
  }
}
```

the html component will look like this

`<div [innerHTML]="content | highlightCode | safeHtml"></div>`

**Comment by DmitryEfimenko** [comment]
I built a [directive](https://github.com/DmitryEfimenko/ngspot/blob/main/packages/common/src/highlight-content/highlight-content.directive.ts) for this. Hopefully, it helps people. Usage:
```html
<pre ngsHighlightContent>
const myVar = 1;
console.log(myVar);
</pre>
```
