### ISSUE TITLE
setTheme does not load theme if `themePath` was not specified in the configuration

### ISSUE THREAD

**Issue by DmitryEfimenko** [MurhafSousli/ngx-highlightjs#247]
#### Reproduction

Steps to reproduce:
1. Open this [StackBlitz](https://stackblitz.com/edit/ngx-highlightjs-mrmpho?file=src/app/app.module.ts) link
2. Observe that theme was not applied because [themePath](https://stackblitz.com/edit/ngx-highlightjs-mrmpho?file=src%2Fapp%2Fapp.module.ts%3AL35,src%2Fapp%2Fhome%2Fhome.component.ts) was not provided in the config.
 
 
#### Expected Behavior

What behavior were you expecting to see?

Theme should be loaded. I think specifying `themePath` in the configuration should be optional.

The application might have conditional logic for loading theme based on user preferences. There's no need to first load a theme that the user does not need, and then switch to a user-preferred theme.

#### Actual Behavior

What behavior did you actually see?

Theme is not loaded due to an error.

StackBlitz doesn't provide a good error stack trace. Here's what I get locally:
> ERROR TypeError: Cannot set properties of undefined (setting 'href')
    at HighlightLoader.setTheme (ngx-highlightjs.mjs:133:36)

This points to [this line of code](https://github.com/MurhafSousli/ngx-highlightjs/blob/master/projects/ngx-highlightjs/src/lib/highlight.loader.ts#L122)
The `_themeLinkElement` is undefined because `loadTheme`, which sets this variable, [never got to run](https://github.com/MurhafSousli/ngx-highlightjs/blob/master/projects/ngx-highlightjs/src/lib/highlight.loader.ts#L51-L53)

#### Environment

- Angular: 15
- ngx-highlightjs: ^7.0.1
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by MurhafSousli** [comment]
Thanks for reporting! here is a fixed [stackblitz ](https://stackblitz.com/edit/ngx-highlightjs-twyuft?file=src%2Fapp%2Fhome%2Fhome.component.ts) with v8.0.0
