### ISSUE TITLE
How to enable instant highlighting?

### ISSUE THREAD

**Issue by Jayadeep-Unico** [MurhafSousli/ngx-highlightjs#25]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?
Windows 10

### Repro steps

My Code:
<textarea [(ngModel)]="highlightCode"></textarea>
"<pre><code #code highlight [textContent]="highlightCode"></code></pre>"

ngAfterViewInit() {
       hljs.highlightBlock(this.codeElement.nativeElement);
}
### Desired functionality
 I want to enable instant highlighting in the code tag if user add text into textarea.

**Comment by MurhafSousli** [comment]
@Jayadeep-Unico 
```html
<textarea [(ngModel)]="code"></textarea>
<pre><code highlight [code]="code"></code></pre>
<!-- or -->
<pre><code highlight [textContent]="code"></code></pre>
```
[live example](https://stackblitz.com/edit/ngx-highlightjs-uv4whj?file=app%2Fhome%2Fhome.component.html)
