### ISSUE TITLE
t.filter is not a function

### ISSUE THREAD

**Issue by nguyenhero** [MurhafSousli/ngx-highlightjs#26]
Today, I tried to use this but i got this error
`core.es5.js:1020 ERROR TypeError: t.filter is not a function`
    `at Object.g [as highlightAuto] (highlight.pack.js:formatted:298)`
    `at HighlightDirective.webpackJsonp.../../../../ngx-highlightjs/ngx-highlightjs.es5.js.HighlightDirective.highlightElement (ngx-highlightjs.es5.js:1578)`
    `at SafeSubscriber._next (ngx-highlightjs.es5.js:1530)`
    `at SafeSubscriber.webpackJsonp.../../../../ngx-highlightjs/ngx-highlightjs.es5.js.SafeSubscriber.__tryOrSetError (ngx-highlightjs.es5.js:611)`
    `at SafeSubscriber.webpackJsonp.../../../../ngx-highlightjs/ngx-highlightjs.es5.js.SafeSubscriber.next (ngx-highlightjs.es5.js:551)`
    `at Subscriber.webpackJsonp.../../../../ngx-highlightjs/ngx-highlightjs.es5.js.Subscriber._next (ngx-highlightjs.es5.js:489)`
    `at Subscriber.webpackJsonp.../../../../ngx-highlightjs/ngx-highlightjs.es5.js.Subscriber.next (ngx-highlightjs.es5.js:453)`
   ` at DoSubscriber.webpackJsonp.../../../../ngx-highlightjs/ngx-highlightjs.es5.js.DoSubscriber._next (ngx-highlightjs.es5.js:1475)`
   ` at DoSubscriber.webpackJsonp.../../../../ngx-highlightjs/ngx-highlightjs.es5.js.Subscriber.next (ngx-highlightjs.es5.js:453)`
    `at TakeSubscriber.webpackJsonp.../../../../ngx-highlightjs/ngx-highlightjs.es5.js.TakeSubscriber._next (ngx-highlightjs.es5.js:1291)`
please help!

**Comment by MurhafSousli** [comment]
@nguyenhero Show me your code

**Comment by nguyenhero** [comment]
Sorry sir, I use wrong markup [language] option . Thank you any way!

**Comment by sergey-morenets** [comment]
Hi @MurhafSousli 

I tried to use your library but I would like to specify the language. If I change your code at stackblitz.com to:

<pre><code highlight [code]="code" [language]="'java'" (highlighted)="onHighlight($event)"></code></pre>

I also get this error "t.filter is not a function". Please advice

**Comment by MurhafSousli** [comment]
@sergey-morenets you post an empty code!

**Comment by sergey-morenets** [comment]
@MurhafSousli 

Any updates on this ticket ?

**Comment by MurhafSousli** [comment]
@sergey-morenets The error is not related to this component. it is just a wrapper. you should open it on the [hljs repo](https://github.com/highlightjs/highlight.js/issues)

But I suggest that you remove the `[language]="'java'"`. it is not necessory because it auto-detect the language for you

**Comment by MurhafSousli** [comment]
@sergey-morenets `[language]` accepts an array of string so it should be  `[language]="['java']"`, but generally it is not necessarily to set because it auto-detects the language for you
