### ISSUE TITLE
(love) Just to tell you how great your software is

### ISSUE THREAD

**Issue by aleluff** [MurhafSousli/ngx-highlightjs#270]
The real issue is maybe that opensource developers don't receive enough gratification.
Thanks to you, creator can build better software

Have a nice day =)

**Comment by MurhafSousli** [comment]
LOL, I think this is a bug 😄 - Thanks @aleluff the issue made my day, have a nice one!

**Comment by aleluff** [comment]
Thanks dude, you too =)
