### ISSUE TITLE
This repo not support pnpm

### ISSUE THREAD

**Issue by BppleMan** [MurhafSousli/ngx-highlightjs#272]
#### Reproduction

```
pnpm i ngx-highlightjk
ng serve
```
 
#### Expected Behavior

run project

#### Actual Behavior

```
./src/main.ts:8:31-53 - Error: Module not found: Error: Can't resolve 'highlight.js' in '/Users/bppleman/coolbox/coolbox-gui/src'

Error: src/main.ts:11:49 - error TS2307: Cannot find module 'highlight.js' or its corresponding type declarations.

11                 fullLibraryLoader: () => import("highlight.js"),
                                                   ~~~~~~~~~~~~~~

```

#### Environment

- Angular: 16.2.0
- ngx-highlightjs: 10.0.0
- Browser(s): nothing
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by MurhafSousli** [comment]
its `ngx-highlightjs`

**Comment by BppleMan** [comment]
> its `ngx-highlightjs`

@MurhafSousli 

That's a typo, but the problem remains

**Comment by thekhegay** [comment]
@MurhafSousli I think the problem is with `highlight.js` resolving. pnpm or yarn pnp doesn't linking it. 

Possible solution is installing directly to project:
`pnpm install highlight.js`

**Comment by thekhegay** [comment]
@MurhafSousli second option: 

add to .npmrc:
`public-hoist-pattern[]=*highlight.js*`

**Comment by thekhegay** [comment]
@MurhafSousli so the idea is to make ngx-highlightjs works like solid package. Library should work like `line-numbers`

example: 
```ts
coreLibraryLoader: () => import('highlight.js/lib/core'),
languages: {
  css: () => import('highlight.js/lib/languages/css'),
  scss: () => import('highlight.js/lib/languages/scss'),
  typescript: () => import('highlight.js/lib/languages/typescript'),
  xml: () => import('highlight.js/lib/languages/xml'),
},
```
should be replaced with:
```ts
coreLibraryLoader: () => import('ngx-highlightjs/highlight-lib'),
languages: {
  css: () => import('ngx-highlightjs/languages/css'),
  scss: () => import('ngx-highlightjs/languages/scss'),
  typescript: () => import('ngx-highlightjs/languages/typescript'),
  xml: () => import('ngx-highlightjs/languages/xml'),
},
```

**Comment by MurhafSousli** [comment]
This is a dependency, how can you receive updates and fixes from the main package then?

**Comment by thekhegay** [comment]
@MurhafSousli
pnpm uses linking to node_modules: [Flat node_modules is not the only way](https://pnpm.io/blog/2020/05/27/flat-node-modules-is-not-the-only-way)

So, for libraries there are 2 approaches:

- Add instructions for pnpm: as i [said](https://github.com/MurhafSousli/ngx-highlightjs/issues/272#issuecomment-1988034567)
    - users needs to install `highlight.js` directly to their projects
    - or add `public-hoist-pattern[]=*highlight.js*` to .npmrc
- Add re exports:
    - ```
       const core = import('highlight.js/lib/core');
       export default core;
      ```
