### ISSUE TITLE
Property '"code"' is incompatible with index signature.

### ISSUE THREAD

**Issue by siddhant-tambe** [MurhafSousli/ngx-highlightjs#276]
#### Reproduction

I have an angular app running `Angular Core v15.2.0`, in which I have installed `ngx-highlightjs v9.0.0` (since `v10.0.0` is incompatible with `Angular <v16`) from npm.
Despite installing it from `npm` using the `npm i ngx-highlightjs@9.0.0`, it failed to install dependent packages, viz., `highlight.js` and `highlightjs-line-numbers.js`.
After installing these manually (by manually matching their versions with `ngx-highlightjs` 's `package.json`), and then doing an `ng build`, I got the following error:

```
Error: node_modules/ngx-highlightjs/lib/highlight.d.ts:31:77 - error TS2344: Type '{ code: { alias: "highlight"; required: false; }; languages: { alias: "languages"; required: false; }; lineNumbers: { alias: "lineNumbers"; required: false; }; }' does not satisfy the constraint '{ [key: string]: string; }'.
  Property '"code"' is incompatible with index signature.
    Type '{ alias: "highlight"; required: false; }' is not assignable to type 'string'.

31     static ɵdir: i0.ɵɵDirectiveDeclaration<Highlight, "[highlight]", never, { "code": { "alias": "highlight"; "required": false; }; "languages": { "alias": "languages"; "required": false; }; "lineNumbers": { "alias": "lineNumbers"; "required": false; }; }, { "highlighted": "highlighted"; }, never, never, false, never>;
                                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I have downgraded to `ngx-highlightjs v8.0.0` where this issue does not exist currently.
So clearly there is something amiss in `v9.0.0`.

Please fix.

#### Environment

- Angular: 15.2.0
- ngx-highlightjs: 9.0.0
- highlight.js: 11.5.1
- highlightjs-line-numbers.js: 2.8.0
- Browser(s): Chrome (latest)
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 11 Pro

**Comment by MurhafSousli** [comment]
For Angular 15, you should use v8.0.0
