### ISSUE TITLE
highlightjs dependency removed from ngx-highlight.js?

### ISSUE THREAD

**Issue by rajeshtarte** [MurhafSousli/ngx-highlightjs#283]
Removed dependency from ngx-hjightjs?

  "dependencies": {
    "highlight.js": "^11.5.1",
    "highlightjs-line-numbers.js": "^2.8.0",
    "tslib": "^2.0.0"
  },

### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

**Comment by MurhafSousli** [comment]
No it was not removed! what is your issue?

**Comment by rajeshtarte** [comment]
Hi MurhafSousli,
thanks for replying back to me

Issue was I followed instructions . but it actually imported alpha version
11.xxx when i checked its package.json file hightlight.js and other
dependencies were not there
then I used laser version like 10.0.0 , which has highlight.js though still
missing few others but atleat now i got hightlight.ts

one more thing for typescript file sometimes it shows Component as keyworrd
and sometimes not

Regards
Rajesh

**Comment by Jonesmann1337** [comment]
> No it was not removed! what is your issue?

Actually it really was removed and highly recommend to add it back to the project's package.json, otherwise we have to manually install this dependency on our own, which doesn't make much sense IMHO
