### ISSUE TITLE
Angular 18 Error: Dynamic require is not supported

### ISSUE THREAD

**Issue by nathan-alvarez0925** [MurhafSousli/ngx-highlightjs#304]
Question after upgrading existing project to Angular 18

I have an Angular 18 library project. I am now seeing the error - Dynamic require of "./core-AX0242KS.js is not supported". I did not see this error in Angular 17.

- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x ] question
```

### OS and Version?
Windows 11

### Versions
Angular 18.2.10
Node 20.17.0


### Repro steps
1. create Standalone component
2. Update import and providers
selector: 'regular-expression-editor',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    MatInputModule,
    MatButtonModule,
    MatSelectModule,
    MatMenuModule,
    MatTooltipModule,
    MatProgressSpinnerModule,
    ClipboardModule,
    HighlightModule,
    FontAwesomeModule,
    ...
  ],
  templateUrl: './regular-expression-editor.component.html',
  styleUrls: [
    '../../../core/styles/style.scss',
    './core/styles/regex-styles.scss',
    './regular-expression-editor.component.scss'
  ],
providers: [
    provideHighlightOptions({
      coreLibraryLoader: () => import('highlight.js/lib/core'),
      lineNumbersLoader: () => import('ngx-highlightjs/line-numbers'),
      languages: {
        typescript: () => import('highlight.js/lib/languages/typescript'),
        css: () => import('highlight.js/lib/languages/css'),
        xml: () => import('highlight.js/lib/languages/xml')
      }
    })
  ]

html

<code class="test-string-text-area"
    [highlight]="testValue()"
    language="typescript">
</code>

### The log given by the failure
[HLJS]  Error: Dynamic require of "./core-AXO242KS.js" is not supported


### Desired functionality
This error does not occur


### Mention any other details that might be useful
<!-- Please include a link to the repo if this is related to an OSS project. -->

**Comment by MurhafSousli** [comment]
Libraries cannot use `import()`, only users of the libraries provide imports in their apps

**Comment by nathan-alvarez0925** [comment]
It is an Angular component library that is trying to use this in one of its components. It worked without issue in Angular 17.

**Comment by MurhafSousli** [comment]
It works until you build the library. the library won't build when you use imports in its code, the import is done in the app side. otherwise I would have use it internally and wouldn't let the user add import manually

**Comment by nathan-alvarez0925** [comment]
How would you suggest using ngx-highlightjs in an Angular 18 library component library? The library component itself is using ngx-highlightjs.

Even if I remove all of the import() and just import the HighLightAuto directive I get the same error.

import { HighlightAuto } from 'ngx-highlightjs';

...
imports: [
...
HighlightAuto
...
]

Throws the same error.
