### ISSUE TITLE
Angular 6 AOT build error -  Function calls are not supported in decorators but 'HighlightModule' was called

### ISSUE THREAD

**Issue by faizalmy** [MurhafSousli/ngx-highlightjs#33]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10 Home

### Versions
![image](https://user-images.githubusercontent.com/1636216/40160843-79044022-59e1-11e8-9633-c0b1ac318f7c.png)

### Repro steps
`ng build --prod`

My code in Module
![image](https://user-images.githubusercontent.com/1636216/40160900-b2fa96b4-59e1-11e8-9e78-c022f9900f0e.png)

### The log given by the failure
![image](https://user-images.githubusercontent.com/1636216/40160815-5bd1a008-59e1-11e8-91d6-7051019cd287.png)

**Comment by lipehnunes** [comment]
Same error here. I'm using `2.0.1`

**Comment by MurhafSousli** [comment]
Guys this bug is fixed in 2.0.2

**Comment by faizalmy** [comment]
How do I pull it using `Yarn`? yarn lib version still `2.0.1`

**Comment by MurhafSousli** [comment]
Ops! I forgot to publish it!! try again it is available now

**Comment by faizalmy** [comment]
Thanks!
