### ISSUE TITLE
Feature Request: Add option to add line numbers

### ISSUE THREAD

**Issue by tommyc38** [MurhafSousli/ngx-highlightjs#35]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] question
```

### Desired functionality

I think it would be sweet if you added the ability to add line numbers as an options to the directive.  See https://github.com/wcoder/highlightjs-line-numbers.js

**Comment by MurhafSousli** [comment]
For now, you can do
```ts
import { Component } from '@angular/core';

declare const hljs: any;

@Component({
  selector: 'app',
  template:  `
    <pre>
        <code highlight [code]="code" (highlighted)="onHighlight($event)"></code>
    </pre>
  `
})
export class HomeComponent {

  code = `.......`;

  onHighlight(e) {
    hljs.initLineNumbersOnLoad();
  }
}
```

Here this [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-kttv1v?file=app/home/home.component.ts)

**Comment by MurhafSousli** [comment]
It would be better if we can implement the lines numbers in this package, if anyone can help on that, PRs are welcome!

**Comment by alissonbovenzo** [comment]
i really excited for this feature, i'll go try do anything about this and i'll go open a PR in few days
[]'s
