### ISSUE TITLE
Registering a custom language when using ngx-highlightjs

### ISSUE THREAD

**Issue by moniuch** [MurhafSousli/ngx-highlightjs#36]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

Not sure how I can `hljs.registerLanguage()` while loading definition from an external file in angular-/cli project. Would you be so kind to provide instructions? Thank you.

**Comment by MurhafSousli** [comment]
Currently you can call that function directly
```ts
declare const hljs: any;

hljs.registerLanguage()
```
I will close this in favor of #37

**Comment by moniuch** [comment]
OK, thanks a lot. Will #36 allow to load a language definition from a ts file? (Stackblitz doesn't allow creating js files)

**Comment by MurhafSousli** [comment]
@moniuch I don't really know how this works! You should ask this question on https://github.com/isagalaev/highlight.js/issues

I updated the docs, in `v2.1.0` you can call hljs functions using `HighlightJS` service.

**Comment by moniuch** [comment]
Great! Thanks. Now I seem to have `isReady` working, but I cannot reset the languages, and also - my custom language appears in the list before I have actually registered it:

https://stackblitz.com/edit/ngx-highlightjs-datatags?file=app%2Fhome%2Fhome.component.ts

Sorry to bother you but I don't quite understand what's going on.

**Comment by MurhafSousli** [comment]
It depends on languages came with the hljs packages you got. I don't know how the languages works. but I get them from here https://highlightjs.org/download/ and include them as mentioned in the docs.
