### ISSUE TITLE
Missing ElementRef

### ISSUE THREAD

**Issue by datalas** [MurhafSousli/ngx-highlightjs#42]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Versions

Angular CLI: 6.0.8
Node: 10.6.0
OS: linux x64
Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.6.8
@angular-devkit/core         0.6.8
@angular-devkit/schematics   0.6.8
@angular/cli                 6.0.8
@angular/common              6.0.9
@angular/core                6.0.9
@angular/platform-browser    6.0.9
@schematics/angular          0.6.8
@schematics/update           0.6.8
rxjs                         6.2.2
typescript                   2.7.2

### Repro steps

Followed the instructions, which seem pretty simple but receive the following error in the logs

### The log given by the failure

ERROR Error: StaticInjectorError(AppModule)[HighlightDirective -> ElementRef]: 
  StaticInjectorError(Platform: core)[HighlightDirective -> ElementRef]: 
    NullInjectorError: No provider for ElementRef!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:1034)
    at resolveToken (core.js:1271)
    at tryResolveToken (core.js:1216)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1113)
    at resolveToken (core.js:1271)
    at tryResolveToken (core.js:1216)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1113)
    at resolveNgModuleDep (core.js:8161)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:8849)
    at resolveDep (core.js:9214)

### Mention any other details that might be useful

Most likely my fault I'm sure, but a little lost and confused

**Comment by MurhafSousli** [comment]
Please add your usage code? reproduce in [stackblitz](https://stackblitz.com/edit/ngx-highlightjs) if possible

**Comment by datalas** [comment]
Sorry I didn't get back to you, I managed to find out what was going on and then the sky fell in and it totally slipped my mind.

The short version is that I'm running Angular from a local copy of node_modules without anything (including this module) installed globally.  This can be made to work, but the Typescript compiler needs to know where the angular modules are installed.

"paths": {
       "@angular/*": ["node_modules/@angular/*"]
 }

in tsconfig.json seems to do the trick.

I don't think it's a bug in this module, but incase it ever crops up again.
