### ISSUE TITLE
Using inside ng-boostrap tab does not work well when switching tabs

### ISSUE THREAD

**Issue by andreidiaconescu** [MurhafSousli/ngx-highlightjs#44]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?

Linux Ubuntu 16.04 LTS

### Versions
Angular CLI: 6.0.5
Node: 8.11.3
Angular: 6.0.0

### Repro steps
1. follow the "Usage" steps from the github repo
2. the highlight works ok
3. integrate ng-boostrap tabs
4. integrate highlight inside one of the tabs: highlight works ok
5. switch tabs: error when going back to a tab with highlighted code, that code "disappears" is not visible any more

### Desired functionality
 - ngx-highlightjs should work also using ng-boostrap tabs

**Comment by MurhafSousli** [comment]
Please add a reproduction using the [stackblitz template](https://stackblitz.com/edit/ngx-highlightjs)
