### ISSUE TITLE
restarting Highlighting automatically

### ISSUE THREAD

**Issue by polly3223** [MurhafSousli/ngx-highlightjs#45]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] question
```

### OS and Version?

Ubuntu 18.04

### Versions

Angular CLI: 6.1.2
Node: 10.3.0
OS: linux x64
Angular: 6.1.0

### Desired functionality

I have an api that responds with json content and I create blog posts with these data.
The problem is that when the user moves to a post by using the angular router (and the json is obtained from the api) the code is not highlighted, then to be able to highlight it the page needs to be reloaded.
How can I restart the highlight when the router moves, with no need to reload the page? 

Thanks in advance!

**Comment by MurhafSousli** [comment]
You don't need to restart highlighting, it should highlight automatically, can you try to make a reproduction for your issue in a [stackbltiz](https://stackblitz.com/edit/ngx-highlightjs)

**Comment by polly3223** [comment]
Here it is: https://stackblitz.com/edit/ngx-highlightjs-9vxqx9
I tried to make it as fast as possible: on the lazy module tab it is supposed to show the highlighted code (retrieved from my api).  Hope this can help.

**Comment by MurhafSousli** [comment]
Just use the `[code]` input, here you go https://stackblitz.com/edit/ngx-highlightjs-x1bjtk?file=src%2Fapp%2Flazy-test%2Flazy-test%2Flazy-test.component.html

**Comment by polly3223** [comment]
oh!!! thank you so much!!  Very good work with the porting by the way!

**Comment by MurhafSousli** [comment]
Welcome!
