### ISSUE TITLE
Highlight with two-way binding

### ISSUE THREAD

**Issue by aaron-bond** [MurhafSousli/ngx-highlightjs#46]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ x ] question
```

### OS and Version?

Windows 10

### Versions

Angular 6.0.0

### Desired functionality

Is there any approach to two-way binding for the editors that works consistently? So far, I've implemented a content editable directive to get me part of the way, but having lots of trouble with carriage returns. 

Has anyone had any luck doing the same?

Here's a stackblitz link to show how I have it working currently: https://stackblitz.com/edit/ngx-highlightjs-kjqjwf

EDIT: as it stands, I think I have this pretty close. I can write into the field and it'll update the content on the model. I still have some issues though.

On the directive, this function runs when I hit Enter after a space (seems intermittent): highlightTextContent(). When that runs, I find that the cursor jumps back to the top of the editable area (because the content has all totally changed). It's possible I could hook into this function (maybe) and reset the cursor after the redraw, but might need a bit of help getting the right properties exposed....

**Comment by MurhafSousli** [comment]
I am not sure what you are trying to accomplish! you cannot make a code editor with this plugin. you should use or embed a code editor instead.
However this is a fixed version [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-x8hnip?file=src%2Fapp%2FcontentEditableModel.ts)
