### ISSUE TITLE
Highlight example code in one line in IE11 with lazy module

### ISSUE THREAD

**Issue by KIAIgorMD** [MurhafSousli/ngx-highlightjs#47]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 7, 8 or 10

### Versions
Angular CLI: 1.7.4/^6
Node: 10.11.0
Angular: 5.2.11/^6
ngx-highlightjs: 1.4.1 and above

### Repro steps

Run stackblitz example or other example/project with lazy module on IE11

![windev1802eval running 2018-09-22 10-36-32](https://user-images.githubusercontent.com/8413395/45914844-67553300-be53-11e8-8daf-d50fdacd73a7.png)

**Comment by MurhafSousli** [comment]
The stackblitz is not necessarily enhanced for IE11.

**Comment by KIAIgorMD** [comment]
> The stackblitz is not necessarily enhanced for IE11.

This problem is not only on the stackblitz, in my project the same problem.
