### ISSUE TITLE
Highlight TextArea

### ISSUE THREAD

**Issue by mrbormeth** [MurhafSousli/ngx-highlightjs#50]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] question
```

### OS and Version?
WINDOWS 10

### Versions
@angular/cli (6.2.4)

### Repro steps
`        <div highlight="textarea">
          <textarea name="codes" [(ngModel)]="itemValue" placeholder="Codes..."></textarea>
        </div>`

### Desired functionality
Would love a way to somehow use ngx-highlightjs directly on a textArea, that way i have a "code editor" directly build in. 
I already made a side by side view, using a textarea and a pre/code box, but the it feels odd that you type one place and reads it in another box. 

Hope that you can help me with my request or maybe point me in the right direction. 

Have a great weekend! 👍

**Comment by rhwilburn** [comment]
Was this ever implemented? Or was it not possible?
