### ISSUE TITLE
languages in HighLightOptions should be of type "HighlightLanguage[]"

### ISSUE THREAD

**Issue by changhuixu** [MurhafSousli/ngx-highlightjs#62]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### Desired functionality
Currently, the type of `languages` is `Func`. I guess it is a typo. It would show intent better if the type is `HighlightLanguage[]`

**Comment by MurhafSousli** [comment]
The current implementation is fine, the function returns a type of `HighlightLanguage[]`
