### ISSUE TITLE
Stackblitz errors

### ISSUE THREAD

**Issue by BenRacicot** [MurhafSousli/ngx-highlightjs#64]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] question
```

### Mention any other details that might be useful
I noticed the [Stackblitz demo](https://stackblitz.com/edit/ngx-highlightjs?file=src%2Fapp%2Fapp.module.ts) seems to have broken links to the `highlight.js/lib/` folder.

I was having trouble getting [my own Stackblitz demo](https://stackblitz.com/edit/design-examples?file=src%2Fapp%2Fforms%2Fforms.component.ts) to work and tracked it back to this. Would you mind taking a look? Thanks for reading.

**Comment by MurhafSousli** [comment]
@BenRacicot `highlight.js/lib/` was for the older version 2.x. I forgot to remove it when I updated the stackblitz template (Now it is fixed).

Your stackblitz is working but you just need to import highlightjs theme, [fixed stackblitz](https://stackblitz.com/edit/design-examples-x6kboy?file=src%2Fscss%2Fstyles.scss).
