### ISSUE TITLE
How to import all languages 

### ISSUE THREAD

**Issue by masoudline** [MurhafSousli/ngx-highlightjs#65]
Hi, I want to import all languages in one place and have the ability to automatically detect the language.

**Comment by MurhafSousli** [comment]
Closing as does not follow the issue template

**Comment by MurhafSousli** [comment]
> I want to import all languages in one place

You still have to import the languages individually as mentioned in the docs.

> have the ability to automatically detect the language

it already detects the language for you

**Comment by Zefling** [comment]
For me, `import` doesn't work, but with `require` it's ok: 

```typescript
export function hljsLanguages() {
    return [
        { name: 'typescript', func: require('highlight.js/lib/languages/typescript') },
        { name: 'javascript', func: require('highlight.js/lib/languages/javascript') },
        { name: 'scss', func: require('highlight.js/lib/languages/scss') },
        { name: 'xml', func: require('highlight.js/lib/languages/xml') }
    ];
}
```
