### ISSUE TITLE
highlightChildren example

### ISSUE THREAD

**Issue by masoudline** [MurhafSousli/ngx-highlightjs#66]
I add highlightChildren to div like this:
`<div class="question-description" highlightChildren  [innerHtml]="question.description | safeHtml"></div>                 
`
but noting work

@MurhafSousli

**Comment by MurhafSousli** [comment]
Please add a reproduction https://stackblitz.com/edit/ngx-highlightjs

**Comment by masoudline** [comment]
in your readme the highlightChildren example not found
==========
highlightChildren directive
Highlight children code elements


<div highlightChildren>
  <pre><code [textContent]="htmlCode"></code></pre>
  <pre><code [textContent]="tsCode"></code></pre>
  <pre><code [textContent]="cssCode"></code></pre>
</div>
Check this [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-children)


i cant add my project in stackblitz

**Comment by MurhafSousli** [comment]
@masoudline Ops! It seems that it was not saved, I made a new one, here you go https://stackblitz.com/edit/ngx-highlightjs-children?file=src/app/home/home.component.html
