### ISSUE TITLE
highlightChildren not working inside [innerHtml]

### ISSUE THREAD

**Issue by masoudline** [MurhafSousli/ngx-highlightjs#67]
@MurhafSousli please see my stackblitz project:

I cannot add highlight js to div with [innerHtml]:

my project in [stackbiltz](https://stackblitz.com/edit/ngx-highlightjs-children-masoud?file=src/app/app.component.ts)

**Comment by ericel** [comment]
facing the same here!
  <div highlightChildren="div pre" (highlighted)="onHighlight($event)">
           <div  [innerHTML]="code"></div>
     </div>
Any solution yet to this?

**Comment by MurhafSousli** [comment]
Fixed in `3.0.2`, here is a [working stackblitz](https://stackblitz.com/edit/ngx-highlightjs-children-masoud-eq4pt9?file=src%2Fstyles.css)
