### ISSUE TITLE
Using HighlightModule in a complex app's submodule

### ISSUE THREAD

**Issue by vasiltabakov** [MurhafSousli/ngx-highlightjs#68]
Here's the scenario:
- huge app
- uses routing
- all routing uses lazy modules
- the app contains a module for previewing highlighted code which uses your lib for highlighting (let's call it CodePreviewModule which contains a component CodePreviewComponent)
- therefore not all modules in the app need the HighlightModule, only the CodePreviewModule needs it

Could you suggest a setup where your lib is only loaded wherever needed. Now it only works if it's loaded in the root module (e.g. app module) and again in the CodePreviewModule.

Will add more details in due time, but first please let me know if this is a config/usage issue. Thanks.

**Comment by MurhafSousli** [comment]
To lazy load this library, the languages must be provided before `HighlightModule` is imported, otherwise it will throw an exception.

**App Module**
```ts
import { HIGHLIGHT_OPTIONS } from 'ngx-highlightjs';

import xml from 'highlight.js/lib/languages/xml';
import scss from 'highlight.js/lib/languages/scss';
import typescript from 'highlight.js/lib/languages/typescript';

export function hljsLanguages() {
  return [
    {name: 'typescript', func: typescript},
    {name: 'scss', func: scss},
    {name: 'xml', func: xml}
  ];
}

@NgModule({
  providers: [
    {
      provide: HIGHLIGHT_OPTIONS,
      useValue: { languages: hljsLanguages }
    }
  ]
})
export class AppModule { }
```

**Feature Module**

```ts
@NgModule({
  imports: [
    HighlightModule
  ],
})
export class FeatureModule { }
```

[working stackblitz](https://stackblitz.com/edit/ngx-highlightjs-4pdf28?file=src/app/app.module.ts)
