### ISSUE TITLE
No languages were registred inside lazy module.

### ISSUE THREAD

**Issue by erichstark** [MurhafSousli/ngx-highlightjs#69]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```
It looks like that HightlightModule can't be used inside lazy loaded module.

### OS and Version?

macOS 10.14.2

### Versions

ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 7.2.2
Node: 10.15.0
OS: darwin x64
Angular: 7.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.2.2
@ngtools/webpack                  7.2.2
@schematics/angular               7.2.2
@schematics/update                0.12.2
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.28.4

### The log given by the failure

core.js:15714 ERROR Error: Uncaught (in promise): Error: [HighlightJS]: No languages were registered!
Error: [HighlightJS]: No languages were registered!
    at new HighlightJS (ngx-highlightjs.js:30)
    at HighlightJS_Factory (ngx-highlightjs.js:227)
    at _callFactory (core.js:21182)
    at _createProviderInstance (core.js:21140)
    at resolveNgModuleDep (core.js:21115)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:21809)
    at resolveNgModuleDep (core.js:21120)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:21809)
    at resolveDep (core.js:22180)
    at createClass (core.js:22054)
    at resolvePromise (zone.js:831)
    at resolvePromise (zone.js:788)
    at zone.js:892
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Object.onInvokeTask (core.js:17280)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:422)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:195)
    at drainMicroTaskQueue (zone.js:601)

**Comment by MurhafSousli** [comment]
If you want to use highlight.js in only one lazy module only, you can just use `HighlightModule.forRoot()`

If you want to use it in multiple lazy module, then register the languages in your root module like so:

```ts
import { HIGHLIGHT_OPTIONS } from 'ngx-highlightjs';

import xml from 'highlight.js/lib/languages/xml';
import scss from 'highlight.js/lib/languages/scss';
import typescript from 'highlight.js/lib/languages/typescript';

export function hljsLanguages() {
  return [
    {name: 'typescript', func: typescript},
    {name: 'scss', func: scss},
    {name: 'xml', func: xml}
  ];
}

@NgModule({
  providers: [
    {
      provide: HIGHLIGHT_OPTIONS,
      useValue: {
        languages: hljsLanguages
      }
    }
  ]
})
```

And then just import `HighlightModule` in your lazy modules

**Comment by erichstark** [comment]
I have tried it that way, but it didnt work.
This is my guildelines lazy module
```
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { HighlightModule } from 'ngx-highlightjs';

import { GuidelinesRoutingModule } from './guidelines-routing.module';
import { ButtonsComponent } from './buttons/buttons.component';

import xml from 'highlight.js/lib/languages/xml';
import scss from 'highlight.js/lib/languages/scss';
import typescript from 'highlight.js/lib/languages/typescript';

export function hljsLanguages() {
  return [
    {name: 'typescript', func: typescript},
    {name: 'scss', func: scss},
    {name: 'xml', func: xml}
  ];
}

@NgModule({
  declarations: [ButtonsComponent],
  imports: [
    CommonModule,
    GuidelinesRoutingModule,
    HighlightModule.forRoot({
      languages: hljsLanguages
    })
  ]
})
export class GuidelinesModule { }
```

**Comment by MurhafSousli** [comment]
Please add a [stackblitz](https://stackblitz.com/edit/ngx-highlightjs) reproduction

**Comment by erichstark** [comment]
Here you are [stackblitz](https://stackblitz.com/edit/ngx-highlightjs-v9kaj9)

**Comment by MurhafSousli** [comment]
Ok, then use the second way, import the language in the root module and highlightjs component in the lazy module

https://stackblitz.com/edit/ngx-highlightjs-g6rxq9?file=src/app/app.module.ts

**Comment by erichstark** [comment]
Ok, I will. Thanks for your time.
