### ISSUE TITLE
less-than and greater-than in html make ngx-highlightjs ineffective

### ISSUE THREAD

**Issue by ZCatherine** [MurhafSousli/ngx-highlightjs#70]
### Bug Report or Feature Request (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

**Comment by ZCatherine** [comment]
![image](https://user-images.githubusercontent.com/22000195/51811731-54fb7200-22e9-11e9-88f8-5dd78921c316.png)

**Comment by MurhafSousli** [comment]
Wrong repo :)

**Comment by ZCatherine** [comment]
Sorry, I didn't understand what you mean. My html contains expressions,and my highlightjs doesn't work after adding the less-than sign(<) of the expression.Could you please give me some solutions?

**Comment by MurhafSousli** [comment]
If you are using `ngx-highlightjs` then store the code you want to highlight in a variable instead of writing it in the template, for further support please try to reproduce it in a stackblitz
