### ISSUE TITLE
Is there anyway to use this module in a featured, lazy loaded module without having to load it in the app.module.ts?

### ISSUE THREAD

**Issue by ericel** [MurhafSousli/ngx-highlightjs#72]
```
- [x ] feature request
- [ x] question
```

### Versions

Angular version 7 cli

### Lazy Loaded modules

Is there anyway to use this module in a featured, lazy loaded module without having to load it in the app.module.ts?
### using with ngx-quill editor

Also I was wondering, in a case where you have a blog post edited by quill editor, which adds just a pre tag for code block.

How can we use this module in such a case to highlight the pre tags code blocks?

Thanks

**Comment by MurhafSousli** [comment]
Yes, you can just import `HighlightModule` in your feature module, however the languages must be imported in your root module as mentioned in this comment https://github.com/MurhafSousli/ngx-highlightjs/issues/69#issuecomment-456815876

I just updated the README for the feature module usage, check it out!

For ngx-quill, first install the recent version `3.0.2` then try `highlightChildren` directive on your content wrapper element, it should automatically highlight them!

**Comment by ericel** [comment]
Thanks man! Works awesomely!
