### ISSUE TITLE
Imports for highlight.js files doesn't works

### ISSUE THREAD

**Issue by Zefling** [MurhafSousli/ngx-highlightjs#78]
For me, `import` doesn't work, but with `require` it's ok.

For example, with Angular 7 without Angular/cli:
```typescript
export function hljsLanguages() {
    return [
        { name: 'typescript', func: require('highlight.js/lib/languages/typescript') },
        { name: 'javascript', func: require('highlight.js/lib/languages/javascript') },
        { name: 'scss', func: require('highlight.js/lib/languages/scss') },
        { name: 'xml', func: require('highlight.js/lib/languages/xml') }
    ];
}
```

**Comment by MurhafSousli** [comment]
Because this is not the proper way! follow the code used in the documentation,

**Comment by Zefling** [comment]
Sorry, but for me, with this, all `func` are `undefined` :

```typescript
import xml from 'highlight.js/lib/languages/xml';
import scss from 'highlight.js/lib/languages/scss';
import typescript from 'highlight.js/lib/languages/typescript';

export function hljsLanguages() {
  return [
    {name: 'typescript', func: typescript},
    {name: 'scss', func: scss},
    {name: 'xml', func: xml}
  ];
}
```

**Comment by MurhafSousli** [comment]
You should use Angular CLI, I don't know how it can work without using `import`

**Comment by Zefling** [comment]
Thanks for this information, but with Angular CLI impossible to build own project. After a week to looking for why, we gave up the intention of ​​having a project with Angular CLI, because it was impossible to modify the config webpack.
