### ISSUE TITLE
Getting "TypeError: language is not a function" in unit tests

### ISSUE THREAD

**Issue by FrancescoBorzi** [MurhafSousli/ngx-highlightjs#79]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Linux Ubuntu 

### Versions
```
Angular CLI: 8.0.1
Node: 10.16.0
OS: linux x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@angular/http                     7.2.15
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0
```

### Repro steps

Create a unit test of a Component that uses the `[highlight]` directive.

### The log given by the failure
> error properties: Object({ ngDebugContext: DebugContext_({ view: Object({ def: Object({ factory: Function, nodeFlags: 674819, rootNodeFlags: 1, nodeMatchedQueries: 0, flags: 0, nodes: [ Object({ nodeIndex: 0, parent: null, renderParent: null, bindingIndex: 0, outputIndex: 0, checkIndex: 0, flags: 1, childFlags: 674819, directChildFlags: 542721, childMatchedQueries: 0, matchedQueries: Object({  }), matchedQueryIds: 0, references: Object({  }), ngContentIndex: null, childCount: 37, bindings: [ Object({ flags: 2, ns: '', name: 'ng-untouched', nonMinifiedName: 'ng-untouched', securityContext: undefined, suffix: undefined }), Object({ flags: 2, ns: '', name: 'ng-touched', nonMinifiedName: 'ng-touched', securityContext: undefined, suffix: undefined }), Object({ flags: 2, ns: '', name: 'ng-pristine', nonMinifiedName: 'ng-pristine', securityContext: undefined, suffix: undefined }), Object({ flags: 2, ns: '', name: 'ng-dirty', nonMinifiedName: 'ng-dirty', securityContext: undefined, suffix: undefined }), Object ...
    at <Jasmine>
    at Object.registerLanguage (http://localhost:9876/_karma_webpack_/webpack:/node_modules/highlight.js/lib/highlight.js:749:1)
    at HighlightJS.push../node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js.HighlightJS.registerLanguage (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js:191:13)
    at http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js:26:1
    at <Jasmine>
    at new HighlightJS (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js:21:1)
    at HighlightJS_Factory (http://localhost:9876/_karma_webpack_/webpack:/node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js:232:114)
    at _callFactory (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:18508:1)
    at _createProviderInstance (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:18466:1)
    at resolveNgModuleDep (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:18441:1)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (http://localhost:9876/_karma_webpack_/webpack:/node_modules/@angular/core/fesm5/core.js:19135:1)

### Mention any other details that might be useful

In my unit test's module, I've imported `HighlightModule.forRoot(highlightOptions)` exactly in the same way I'm using it in my main `app.module.ts` (there it works).

**Comment by MurhafSousli** [comment]
The library does not have unit tests, and I cannot help on that regards. if you think it can fixed from this package and you know how to fix it, PRs are welcome!

But this is not a bug

**Comment by FrancescoBorzi** [comment]
@MurhafSousli of course this is a bug since using this directive breaks the tests

**Comment by HYrelav** [comment]
I get the same error if I use the curly-brackets like { xml } in the import, I removed the curly-brackets and the error left.
example: import xml from 'highlight.js/lib/languages/xml';

**Comment by FrancescoBorzi** [comment]
@HYrelav thanks for sharing this, however for me it doesn't work with or without curly-braces.

This is how I'm using it:

```
import sql from 'highlight.js/lib/languages/sql';

export function hljsLanguages() {
  return [
    { name: 'sql', func: sql },
  ];
}

export const highlightOptions = {
  languages: hljsLanguages,
};
```

also I've tested both targetting `es5` and `es6`, it's broken on both.

**Comment by tommysitu** [comment]
@FrancescoBorzi I had the same issue but it works after I changed my `tsconfig.spec.json` to use `es2015` module for the compiler: 
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
//    "module": "commonjs",
    "module": "es2015",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts",
    "polyfills.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

**Comment by FrancescoBorzi** [comment]
@tommysitu thanks a lot, that works

**Comment by mhamel06** [comment]
I also found that importing the language with the * syntax also works in tests. e.g.
```
import * as xml from 'highlight.js/lib/languages/xml';
```
