### ISSUE TITLE
Do not throw an error if [highlight] input got an undefined value

### ISSUE THREAD

**Issue by westor21** [MurhafSousli/ngx-highlightjs#81]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```
### OS and Version?
Windows 7

### Versions
Angular CLI: 7.3.9
Node: 8.11.1
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cdk                      7.3.7
@angular/cli                      7.3.9
@angular/material                 7.3.7
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.1
typescript                        3.2.4
webpack                           4.29.0

### Repro steps
I use the directive in a lazy module and as stream:
`<pre><code #code *ngIf="showCode" [highlight]="code$ | async"></code></pre>`

### The log given by the failure

The directive does it's work, but I see the following console error:

```
ERROR TypeError: Cannot read property 'replace' of null
    at escape (highlight.js:62)
    at Object.highlightAuto (highlight.js:624)
    at HighlightJS.push../node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js.HighlightJS.highlightAuto (ngx-highlightjs.js:91)
    at ngx-highlightjs.js:288
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at NgZone.push../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:17258)
    at Highlight.push../node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js.Highlight.highlightElement (ngx-highlightjs.js:283)
    at Highlight.push../node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js.Highlight.ngOnChanges (ngx-highlightjs.js:260)
    at checkAndUpdateDirectiveInline (core.js:22095)
```

### Desired functionality
no error

**Comment by MurhafSousli** [comment]
Please provide a [stackblitz](https://stackblitz.com/edit/ngx-highlightjs) reproduction

**Comment by westor21** [comment]
Here you are. Please have a look at console.
https://stackblitz.com/edit/ngx-highlightjs-bug-with-stream

**Comment by MurhafSousli** [comment]
@westor21 You are passing an undefined value in the beginning then after 1 second you pass the valid string value.
Simply check if `html$` is defined in your template, here is the fix https://stackblitz.com/edit/ngx-highlightjs-bug-with-stream-1dwyhn?file=src/app/home/home.component.html

**Comment by westor21** [comment]
Well, thank you. But wouln'd it be cleaner, to make either ngx-highlightjs or highlight.js a little bit more robust to not crash when used with undefined or null values?

**Comment by MurhafSousli** [comment]
Well, one of the features I was thinking to introduce is a directURL input to fetch code from a URL.

However for this issue, it is not a bug. It is the developer responsibility to provide valid input values, any library will break if you provide invalid inputs
