### ISSUE TITLE
Cannot read property 'highlightAuto' of undefined

### ISSUE THREAD

**Issue by belyan** [MurhafSousli/ngx-highlightjs#82]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Windows 10

### Versions
Angular CLI: 8.0.3
Node: 10.13.0
OS: win32 x64
Angular: 8.0.2

### Repro steps
```
<pre><code [highlight]="someCode"></code></pre>
```

### The log given by the failure
```
CodeComponent.html:2 ERROR TypeError: Cannot read property 'highlightAuto' of undefined
    at ngx-highlightjs.js:288
    at ZoneDelegate.push.../../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke (zone.js:391)
    at Zone.push.../../node_modules/zone.js/dist/zone.js.Zone.run (zone.js:150)
    at NgZone.push.../../node_modules/@angular/core/fesm5/core.js.NgZone.runOutsideAngular (core.js:24308)
    at Highlight.push.../../node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js.Highlight.highlightElement (ngx-highlightjs.js:283)
    at Highlight.push.../../node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js.Highlight.ngOnChanges (ngx-highlightjs.js:260)
    at checkAndUpdateDirectiveInline (core.js:19337)
    at checkAndUpdateNodeInline (core.js:27597)
    at checkAndUpdateNode (core.js:27559)
    at debugCheckAndUpdateNode (core.js:28193)
```

**Comment by MurhafSousli** [comment]
Please add a reproduction using this [stackblitz](https://stackblitz.com/edit/ngx-highlightjs)

**Comment by belyan** [comment]
The problem occurred when I have updated Node.js from version 8.16.0 to 10.16.0. I don't know which version is installed on StackBlitz.

**Comment by MurhafSousli** [comment]
Ok, for let's close this as it does have enough info, feel free to reopen if you get the problem again

**Comment by joeskeen** [comment]
@belyan did you ever figure out what caused this error?  I also got this error after updating my project from Angular 6 to 8.  I looked at my `package-lock.json` and the version of `highlight.js` is unchanged (9.16.2).

**Comment by joeskeen** [comment]
For posterity's sake, I think I was using an old way of initializing the library:
![image](https://user-images.githubusercontent.com/12286274/77134897-ae16ef80-6a2e-11ea-8eaa-bb17e87a5504.png)
After changing to the way documented in the current version of the Readme, it still didn't work.  This is what finally worked:
![image](https://user-images.githubusercontent.com/12286274/77135246-3cd83c00-6a30-11ea-961c-82ce79601e13.png)

```ts
export function getHljsLanguages() {
    return [
        {name: 'typescript', func: () => import('highlight.js/lib/languages/typescript')},
        {name: 'scss', func: () => import('highlight.js/lib/languages/scss')},
        {name: 'xml', func: () => import('highlight.js/lib/languages/xml')}
    ];
}

@NgModule({
    imports: [SharedModule, ExampleModule, ComponentsRouterModule, HighlightModule],
    providers: [
        ApplicationInsightsService,
        {
            provide: HIGHLIGHT_OPTIONS,
            useValue: {languages: getHljsLanguages, lineNumbers: true}
        }
    ],
```
