### ISSUE TITLE
HighlightResult returns `relevance` instead of `r`

### ISSUE THREAD

**Issue by Humberd** [MurhafSousli/ngx-highlightjs#84]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

The `(highlighted)` response interface has a field `r`, however, the js object has a field `relevance`

**Comment by MurhafSousli** [comment]
Actually, it seems that r property has been removed from the response by `highlight.js` package, there is no `relevance` property as I see here https://stackblitz.com/edit/ngx-highlightjs-v4
