### ISSUE TITLE
TypeError: language is not a function

### ISSUE THREAD

**Issue by andreacavagna01** [MurhafSousli/ngx-highlightjs#85]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
macOS Mojave

### Repro steps
By installing the library with Option 1 method.
Languages imported in func are undefined

### The log given by the failure
```
ERROR TypeError: language is not a function
    at Object.registerLanguage (highlight.js:752)
    at HighlightJS.push../node_modules/ngx-highlightjs/fesm5/ngx-highlightjs.js.HighlightJS.registerLanguage (ngx-highlightjs.js:193)
    at ngx-highlightjs.js:28
    at Array.map (<anonymous>)
    at new HighlightJS (ngx-highlightjs.js:23)
    at HighlightJS_Factory (ngx-highlightjs.js:234)
```

### Desired functionality

It should load languages correctly
my code is the same as the demo:
``` import typescript from 'highlight.js/lib/languages/typescript';

/**
 * Import every language you wish to highlight here
 * NOTE: The name of each language must match the file name its imported from
 */
export function hljsLanguages() {
  return [
    {name: 'typescript', func: typescript},
    {name: 'scss', func: scss},
    {name: 'xml', func: xml}
  ];
}```


### Mention any other details that might be useful
<!-- Please include a link to the repo if this is related to an OSS project. -->

**Comment by MurhafSousli** [comment]
Please add a reproduction [stackblitz](https://stackblitz.com/edit/ngx-highlightjs)

**Comment by andreacavagna01** [comment]
it work on stackblitz, on mine code does not load languages. don't know why

**Comment by andreacavagna01** [comment]
basically if I try to log each language in **  {name: 'typescript', func: typescript},** from ** import typescript from 'highlight.js/lib/languages/typescript'; ** i will have an undefined

**Comment by MurhafSousli** [comment]
It is unclear, please provide a stackblitz

**Comment by Douglas12ds** [comment]
Having the exact same problems. Looks like the highlight.js got updated and this broke up ngx-highlight.
