### ISSUE TITLE
All tests are failing after updating to 4.0.0

### ISSUE THREAD

**Issue by FrancescoBorzi** [MurhafSousli/ngx-highlightjs#97]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
Linux Ubuntu 18.04

### Versions

```
Angular CLI: 8.3.19
Node: 10.16.0
OS: linux x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.19
@angular-devkit/build-angular     0.803.19
@angular-devkit/build-optimizer   0.803.19
@angular-devkit/build-webpack     0.803.19
@angular-devkit/core              8.3.19
@angular-devkit/schematics        8.3.19
@angular/cli                      8.3.19
@ngtools/webpack                  8.3.19
@schematics/angular               8.3.19
@schematics/update                0.803.19
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
```

### Repro steps

Suppose having an element that uses `[highlight]="myCode"` and that you automatically populate the content of `myCode` on some button click.

If you write a simple test that clicks the button and expects the element with `[highlight]` to have the proper content, it will fail.

### Desired functionality

As it was before 4.0.0, you just had to trigger the event (e.g. a button click, input change, etc..) and then use `fixture.detectChanges()` to automatically refresh the view.

### Mention any other details that might be useful

All the tests of my app are broken if I try to use version 4.0.0:

https://github.com/azerothcore/Keira3/pull/232

**Comment by MurhafSousli** [comment]
First, highlighting is done async, so you probably need to use the `(highlighted)` output instead

**Comment by FrancescoBorzi** [comment]
@MurhafSousli can you please show me an example?

**Comment by FrancescoBorzi** [comment]
@MurhafSousli can you please show me an example?

**Comment by MurhafSousli** [comment]
I don't know what is your test case, but you can check the unit testing of highlight component [highlight.spec.ts](https://github.com/MurhafSousli/ngx-highlightjs/blob/master/projects/ngx-highlightjs/src/lib/highlight.spec.ts)

https://github.com/MurhafSousli/ngx-highlightjs/blob/9491d7704e3f37bc0788607813fb628437b1c881/projects/ngx-highlightjs/src/lib/highlight.spec.ts#L56-L63

Here I test it against the loader service which lazy-load hljs script then it highlights the text

**Comment by FrancescoBorzi** [comment]
why is `tick(500);` needed?

**Comment by MurhafSousli** [comment]
`tick(500)` checks for the result after 500ms, (assuming the library is lazy-loaded and the text is highlighted), google about `fakeAsync` and `tick`

**Comment by FrancescoBorzi** [comment]
@MurhafSousli sorry for the late answer, I know what `tick` is used for, my question was: why is `tick()` needed now where it was fine without it in version 3.x.x. Because of this, we are still struggling to update our app to version 4.x.x.

Even using an `await fixture.whenStable()`, which apparently also solves the issue, our unit tests are completely unstable because they randomly fail. And we have plenty of them. Is there a way to prevent this? How are you unit-testing your apps that rely on `ngx-highlightjs` ?

**Comment by FrancescoBorzi** [comment]
@MurhafSousli can you please help with this?

**Comment by MurhafSousli** [comment]
I only use it for simple demo apps that is meant for documentation which does not have unit tests

**Comment by FrancescoBorzi** [comment]
@MurhafSousli this is still blocking our app. We cannot upgrade it from version 3.x to version 4.x because and we cannot upgrade highlightjs from 9 to the latst. Can you please fix this issue and make possible to test the 4.x just like it was with the 3.x ?
