### ISSUE TITLE
Highlight code inside [innerHTML] attribute

### ISSUE THREAD

**Issue by MrBandaruk** [MurhafSousli/ngx-highlightjs#98]
Hello. I'm using editor and get HTML output from it. How can I highlight code inside [innerHTML] attribute. I can't use highlight directive. 

```html
<div class="text" [innerHTML]="article.text"></div>
```
HTML inside [innerHTML]:
```html
<pre>
  <code class="language-javascript">
  // code
  </code>
</pre>
```

**Comment by MurhafSousli** [comment]
No that won't work well for you! if you want a code editor, you should use vscode. this package is just a wrapper for highlight.js library and it does not offer anything more than that
